APIMANAGER-5357 issue fixed. - Public JIRA URL https://wso2.org/jira/browse/APIMANAGER-5357. The issue was data publisher feature missing in the api-publisher profile, hence throw NoClassDefFoundError at server startup. The missing feature added to the profile generation.